amplimindcc/frontend

- src/pages/Commit/Commit.tsx
Weiß nicht, ob die doppelte Überprüfung nötig ist, ob es eine zip-Datei ist.
> 31 commit upload check for zip files

- src/pages/Admin/components/Users/Users.tsx
- src/services/toast.ts
> 24 admin panel user management toasts

- src/pages/Login/Login.tsx
> change type to success

- src/interfaces/UsersTableElement.ts
- src/pages/Admin/components/Users/Users.tsx
> 65 remove status column from user manage

- src/pages/Admin/components/Users/Users.tsx
> now displays error text parsed from JSON

- src/services/toast.ts
> 97 add JSDoc to httpError service

- src/services/toast.ts
> 105 improve toast service docu

- README.md
> 124 Link Framework Documentation in README

- src/interfaces/Action.ts
- src/pages/Admin/components/Users/Users.tsx
> 123 Remove Admin Demote and Elevate

- src/interfaces/Action.ts
- src/pages/Admin/components/Users/Users.tsx
- src/services/toast.ts
> 120 Remove Id from Error Messages before going in PROD

- src/interfaces/UsersTableElement.ts
- src/pages/Admin/components/Users/Users.tsx
> 119 Re add status column to user management

- src/App.tsx
- src/pages/Logout/Logout.tsx
- src/services/user.ts
> 133 Add Logout Page

- package-lock.json
- package.json
- src/components/PasswordStrengthMeter/PasswordStrengthMeter.css
- src/components/PasswordStrengthMeter/PasswordStrengthMeter.scss
- src/components/PasswordStrengthMeter/PasswordStrengthMeter.tsx
- src/interfaces/PasswordStatus.ts
- src/interfaces/SpecialCharRegex.ts
- src/pages/Invite/Invite.tsx
- src/pages/ResetPassword/ResetPassword.tsx
- src/services/passwordService.ts
> 138 password strength check and criteria

- src/pages/Admin/components/Wrapper/Navigation/Navigation.css
- src/pages/Admin/components/Wrapper/Navigation/Navigation.scss
- src/pages/Admin/components/Wrapper/Navigation/Navigation.tsx
> 68 Username in Navbar

- src/interfaces/Action.ts
- src/interfaces/ConfirmationModalData.ts
- src/interfaces/UsersTableElement.ts
- src/pages/Admin/components/ConfirmationModal/ConfirmationModal.tsx
- src/pages/Admin/components/Users/Users.tsx
- src/services/user.ts
> 118 add invite renewal

- src/services/toast.ts
> 174 Modify Toast Service to accept JSX

- src/App.tsx
- src/components/AdminAuthWrapper/AdminAuthWrapper.tsx
- src/components/AuthProvider.tsx
- src/components/AuthenticatedContext.tsx
- src/components/AuthorizedContext.tsx
- src/components/ContentWrapper/ContentWrapper.tsx
- src/components/UserAuthWrapper/UserAuthWrapper.tsx
- src/pages/Invite/Invite.tsx
- src/pages/Login/Login.tsx
- src/pages/Logout/Logout.tsx
- src/services/serviceHelper.ts
> 186 navbar doesnt disappear on logout

- src/pages/Login/Login.tsx
> 169 limit login attempts

- src/pages/Login/Login.test.jsx
> 193 add test case for rate limiting on l

- mocks/api.ts
- src/pages/ResetPassword/ResetPassword.test.jsx
- src/pages/ResetPassword/ResetPassword.tsx
- src/pages/ResetPasswordRequest/ResetPasswordRequest.test.jsx
- src/pages/ResetPasswordRequest/ResetPasswordRequest.tsx
> add tests for password reset

- .env.development
- .env.production
- .env.test
- README.md
- mocks/api.ts
- src/components/Loader/Loader.tsx
- src/pages/Invite/Invite.test.jsx
- src/pages/Invite/Invite.tsx
- src/pages/Login/Login.test.jsx
- src/pages/ResetPassword/ResetPassword.test.jsx
- src/pages/ResetPasswordRequest/ResetPasswordRequest.test.jsx
- src/services/challenge.ts
- src/services/project.ts
- src/services/serviceHelper.ts
- src/services/submission.ts
- src/services/user.ts
- src/vite-env.d.ts
- tsconfig.json
> 208 invite tests

- package-lock.json
- src/components/LangProvider.tsx
- src/pages/Invite/Invite.test.jsx
- src/pages/Login/Login.test.jsx
- src/pages/Logout/Logout.test.jsx
- src/pages/ResetPassword/ResetPassword.test.jsx
- src/pages/ResetPasswordRequest/ResetPasswordRequest.test.jsx
> fix tests for i18n

- mocks/api.ts
- src/pages/Admin/components/ConfirmationModal/ConfirmationModal.tsx
- src/pages/Admin/components/Users/Users.test.jsx
- src/pages/Admin/components/Users/Users.tsx
> 201 user management tests

- mocks/api.ts
- src/components/ContentWrapper/ContentWrapper.test.jsx
- src/components/ContentWrapper/Footer/Footer.tsx
- src/components/ContentWrapper/Navigation/Navigation.tsx
- src/components/LanguageSelector/LanguageSelector.tsx
- src/components/LoaderPage/LoaderPage.tsx
- src/locales/de/main.json
- src/locales/en/main.json
> 203 navbar tests

- .github/workflows/pipeline.yaml
> conditional commit and push

- src/components/LangProvider/LangProvider.tsx
> fix broken initial language

- src/App.css
- src/App.scss
- src/pages/Commit/Commit.css
- src/pages/Commit/Commit.scss
- src/pages/Commit/Commit.tsx
WQHD-Bildschirm (2560x1440)
FHD (1920x1080)
FHD (1080x1920)
> 272 fix spacings for long description texts on commit page

- src/locales/de/admin.json
- src/locales/de/userProject.json
- src/locales/en/admin.json
- src/locales/en/userProject.json
- src/pages/Admin/components/Submissions/Submissions.tsx
- src/pages/Commit/Commit.test.jsx
- src/pages/Commit/Commit.tsx
- src/services/submission.ts
> add functionality to result button

- src/locales/de/userProject.json
- src/locales/en/userProject.json
- src/pages/Commit/Commit.test.jsx
- src/pages/Commit/Commit.tsx
> add handling for 503 and 413

- src/locales/de/logout.json
- src/locales/en/logout.json
- src/pages/Commit/Commit.tsx
- src/pages/Commit/components/LocalizedFileInput.tsx
- src/pages/Logout/Logout.test.jsx
- src/pages/Logout/Logout.tsx
> 330 move id in localizedfileinput to pro

- src/App.tsx
> add wildcard route to match all unmatched routes

- src/locales/de/admin.json
- src/locales/en/admin.json
- src/pages/Admin/components/Challenges/Challenges.tsx
> 335 refine errors on deleting challenge

- README.md
> remove milkdown, mark act as outdated and add tinymce

- src/components/PasswordStrengthMeter/PasswordStrengthMeter.css
- src/components/PasswordStrengthMeter/PasswordStrengthMeter.scss
> add margin to password strength meter
